### ISSUE TITLE
"Detected 2 diacritics" causes server.exe to stop scanning the game.

### ISSUE THREAD

**Issue by auddie2015** [NiHoel/Anno1800UXEnhancer#6] opened 2020-09-04 22:30 UTC
Sever.exe will output "Detected 2 diacritics" (sometimes it says 4 instead of 2) and then stop reading the Anno 1800 screen.  None of my islands have names with markings over any letters or any non Latin alphabet letters. I can't find what is causing the pause.

Version: Anno1800UXEnhancer_v4.3
Anno 1800 is fully updated as well.

**Comment by NiHoel** [comment] 2020-09-05 09:35
Please follow the steps under "Troubleshooting" -> "f you encounter any bug, ..." and send me the files and output.

**Comment by auddie2015** [comment] 2020-09-05 13:47
Ok, back with my find. My game and my calculator are both in English but I do have an accented letter in my name, Françoise. I do not see my name appearing on any of the information windows but everything works fine until it seems a quest is given but I also don't see my name displayed there either.

Screen is 1920x1080
[ServerOutput.txt](https://github.com/NiHoel/Anno1800UXEnhancer/files/5178157/ServerOutput.txt)


request received: lang=english
973045
request received: lang=english
973045
request received: lang=english
973045
request received: lang=english
973045
request received: lang=english
1.03243e+06
request received: lang=english
1.03243e+06
request received: lang=english
2.09969e+06
request received: lang=english
2.09969e+06
request received: lang=english
731021
request received: lang=english
1.37579e+06
request received: lang=english
1.37579e+06
request received: lang=english
request received: lang=english
request received: lang=english
request received: lang=english
Estimating resolution as 133
Detected 2 diacritics

**Comment by NiHoel** [comment] 2020-09-05 17:59
What happens if you rename the island?

Can you send me the images generated in debug_images?

**Comment by auddie2015** [comment] 2020-09-05 18:23
I did a Google search and there isn't a way to rename your character. 

I don't understand the debug_images request. The Statistic Extractor is not denerating any logs or images that I can find.  I am checking island names to make sure that's not a problem but they should be unique enough names as to not confuse the program. Back shortly.

**Comment by NiHoel** [comment] 2020-09-05 18:39
The calculator only inspects important parts of each screenshot. Normally, it should never read your profile name. I assume that the issue is more related to island names not properly being processed.

**Comment by auddie2015** [comment] 2020-09-05 19:03
No, I must have missed that parameter. Sorry. I do think it was that long island name, Ganso Com Pernas, because it's not doing it anymore without that name. It's running just fine.

**Comment by NiHoel** [comment] 2020-09-05 19:05
Maybe there were some artifacts due to the image next to the name. I close this issue for now.

**Closed by NiHoel** 2020-09-05 19:05 UTC

**Comment by auddie2015** [comment] 2020-09-05 19:23
Thanks! I do not ever want to play Anno 1800 without this again. This thing is awesome!

**Comment by NiHoel** [comment] 2020-09-05 20:20
In spite of ingame statistics?

**Comment by auddie2015** [comment] 2020-09-06 01:39
If only you could write a program to deliver rum...
